### ISSUE TITLE
Error on Requesting Proof in Verifier App

### ISSUE THREAD

**Issue by rkirandas** [Yoroitchi/AriesWebApp#4]
On Verifier App clicking button Request Proof Name John/Dave gets an error

EntryPointNotFoundException: Unable to find an entry point named 'indy_generate_nonce' in DLL 'indy'.

![Capture](https://user-images.githubusercontent.com/62564910/172534144-24b3ae18-144c-419d-963d-ace7993060e2.PNG)

Is there any addtnl setup i should've done

@Yoroitchi

**Comment by x0axz** [comment]
Have you established a Verifier-Holder connection?

**Comment by rkirandas** [comment]
@x0axz 

Yes  I was able to issue credentials with no problem.

Also please consider this also if you have time
https://github.com/hyperledger/aries-mobile-agent-xamarin/issues/63#issuecomment-1149467396
